In [2]:
!pip install Pillow

     |████████████████████████████████| 3.0 MB 991 kB/s eta 0:00:01     |██████████████████████████████  | 2.8 MB 991 kB/s eta 0:00:01


In [5]:
!pip install tensorflow

  Using cached protobuf-3.17.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
  Using cached tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached wrapt-1.12.1-cp38-cp38-linux_x86_64.whl
  Using cached h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Using cached grpcio-1.34.1-cp38-cp38-manylinux2014_x86_64.whl (4.0 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x

In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 15 14:49:19 2019

@author: krish.naik
"""

# Face Recognition

# Importing the libraries
from PIL import Image
from tensorflow.keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from tensorflow.keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Tariq'
        elif(pred[0][2]>0.5):
            name='Zeeshan'
        if(pred[0][2]>0.5):
            name='Siddique'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

       



<>:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
/tmp/ipykernel_14732/2932175487.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[4.3706777e-08 1.0000000e+00 0.0000000e+00]]


QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to tar

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to target thread (0x558ff30d4d60)

QObject::moveToThread: Current thread (0x558ff30d4d60) is not the object's thread (0x558fed3029c0).
Cannot move to tar

[[4.7385066e-21 1.0000000e+00 0.0000000e+00]]
[[7.7832364e-21 1.0000000e+00 0.0000000e+00]]
[[3.454354e-15 1.000000e+00 0.000000e+00]]
[[6.1776014e-08 9.9999988e-01 0.0000000e+00]]
[[3.2396227e-07 9.9999964e-01 0.0000000e+00]]
[[1.278078e-04 9.998722e-01 0.000000e+00]]
[[7.1266122e-06 9.9999285e-01 0.0000000e+00]]
[[7.4588047e-07 9.9999928e-01 0.0000000e+00]]
[[0.03235591 0.96764404 0.        ]]
[[1.000000e+00 6.683639e-14 0.000000e+00]]
[[1.0000000e+00 2.9494088e-21 0.0000000e+00]]
[[1.000000e+00 8.418686e-10 0.000000e+00]]
[[1.0000000e+00 6.1528077e-10 0.0000000e+00]]
[[9.9998832e-01 1.1657929e-05 0.0000000e+00]]
[[0.9942984  0.00570167 0.        ]]
[[2.6515616e-05 9.9997354e-01 0.0000000e+00]]
[[1.0000000e+00 1.0958659e-08 0.0000000e+00]]
