In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_digits
digits = load_digits()

In [6]:
dict(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [7]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [9]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/home/mahartariq/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [10]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9851851851851852

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9685185185185186

# KFold cross validation


In [14]:
# Basic Example

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
for train,test in kf.split([3,4,11,2,1,75,22,43,130,11,284]):
    print(train,test)

[ 4  5  6  7  8  9 10] [0 1 2 3]
[ 0  1  2  3  8  9 10] [4 5 6 7]
[0 1 2 3 4 5 6 7] [ 8  9 10]


In [18]:
# Use KFold for our digits example

In [19]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [22]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)


score_logistic = []
score_svm = []
score_random_forest = []

for train,test in folds.split(digits.data, digits.target):
    x_train,x_test,y_train,y_test = digits.data[train],digits.data[test],digits.target[train],digits.target[test]
    score_logistic.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_random_forest.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

/home/mahartariq/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/mahartariq/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

In [23]:
score_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [24]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [25]:
score_random_forest

[0.9232053422370617, 0.9415692821368948, 0.9332220367278798]

# cross_val_score function

In [26]:
from sklearn.model_selection import cross_val_score

In [28]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=5)

/home/mahartariq/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/mahartariq/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logis

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [29]:
cross_val_score(SVC(),digits.data,digits.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [30]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=4)

array([0.92888889, 0.91314031, 0.97104677, 0.91759465])

In [31]:
#tuning

In [37]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=5)
np.average(score1)

0.9048823893531415

In [38]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=5)
np.average(score2)

0.9254596100278553

In [39]:
score3 =cross_val_score(RandomForestClassifier(n_estimators=30),digits.data,digits.target,cv=5)
np.average(score3)

0.9276756422160322

In [40]:
score4 =  cross_val_score(RandomForestClassifier(n_estimators=55),digits.data,digits.target,cv=5)
np.average(score4)

0.93491643454039

# Random Forest Classifer and Figured having 55 trees in Random Forest gives best Results.