In [22]:
import tensorflow as tf

In [23]:
from tensorflow.keras.datasets import mnist
(train_images,train_labels), (test_images,test_labels) = mnist.load_data()

In [24]:
(train_images,train_labels), (test_images,test_labels) = mnist.load_data()

In [25]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [26]:
train_images[0].shape

(28, 28)

In [27]:
train_images[0].ndim

2

In [28]:
train_images.shape

(60000, 28, 28)

In [29]:
test_images.shape

(10000, 28, 28)

In [30]:
train_labels[0]

5

In [31]:
train_labels[2]

4

In [32]:
train_labels[9]

4

In [33]:
from tensorflow.keras import models
from tensorflow.keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu',input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

In [34]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [35]:
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32')/255
test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32')/255

In [36]:
train_images.shape

(60000, 784)

In [37]:
train_labels.shape

(60000,)

In [38]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [39]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [40]:
network.fit(train_images,train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 0.2551 - accuracy: 0.9266
Epoch 2/5
469/469 [==============================] - 4s 8ms/step - loss: 0.1038 - accuracy: 0.9692
Epoch 3/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0680 - accuracy: 0.9800
Epoch 4/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0502 - accuracy: 0.9851
Epoch 5/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0375 - accuracy: 0.9884


In [41]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc ',test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0710 - accuracy: 0.9794
test_acc  0.9793999791145325


In [43]:
network.predict(test_images)[0]

array([4.1978927e-09, 1.4917089e-09, 3.4522993e-05, 3.9721817e-05,
       2.1255817e-11, 2.4983021e-07, 8.6137742e-14, 9.9991775e-01,
       2.8748000e-06, 4.9222836e-06], dtype=float32)

In [48]:
import matplotlib.pyplot as plt
digit = train_images[4]
print(digit)

#plt.imshow(digit, cmap=plt.cm.binary)
#plt.show()

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [46]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_accuracy ',test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0710 - accuracy: 0.9794
test_accuracy  0.9793999791145325
